[package]
name = "fastgit"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
git2 = { version = "0.20.4", features = ["https", "ssh"] }
ratatui = "0.30.0"
tokio = { version = "1.49.0", features = ["full"] }
